/*
 * Employee wage sum
 *
 * Wage sum - demo application with GO language
 *
 * API version: 0.2.0
 * Contact: lsmhun@github
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"context"
	"errors"
	"net/http"

	openapi "github.com/lsmhun/wage-sum-server/internal/pkg/openapi"
)

// SalApiService is a service that implements the logic for the SalApiServicer
// This service should implement the business logic for every endpoint for the SalApi API.
// Include any external packages or services that will be required by this service.
type SalApiService struct {
}

// NewSalApiService creates a default api service
func NewSalApiService() openapi.SalApiServicer {
	return &SalApiService{}
}

// GetSalByEmpId - Find sal by ID
func (s *SalApiService) GetSalByEmpId(ctx context.Context, empId string) (openapi.ImplResponse, error) {
	// TODO - update GetSalByEmpId with the required logic for this service method.
	// Add api_sal_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response openapi.Response(200, string{}) or use other options such as http.Ok ...
	//return openapi.Response(200, string{}), nil

	//TODO: Uncomment the next line to return response openapi.Response(400, {}) or use other options such as http.Ok ...
	//return openapi.Response(400, nil),nil

	//TODO: Uncomment the next line to return response openapi.Response(404, {}) or use other options such as http.Ok ...
	//return openapi.Response(404, nil),nil

	return openapi.Response(http.StatusNotImplemented, nil), errors.New("GetSalByEmpId method not implemented")
}

// GetWageSumByMgrId - Find sum sal by manager ID
func (s *SalApiService) GetWageSumByMgrId(ctx context.Context, empId int64) (openapi.ImplResponse, error) {
	// TODO - update GetWageSumByMgrId with the required logic for this service method.
	// Add api_sal_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response openapi.Response(200, string{}) or use other options such as http.Ok ...
	//return openapi.Response(200, string{}), nil

	//TODO: Uncomment the next line to return response openapi.Response(400, {}) or use other options such as http.Ok ...
	//return openapi.Response(400, nil),nil

	//TODO: Uncomment the next line to return response openapi.Response(404, {}) or use other options such as http.Ok ...
	//return openapi.Response(404, nil),nil

	return openapi.Response(http.StatusNotImplemented, nil), errors.New("GetWageSumByMgrId method not implemented")
}

// UpdateSalWithForm - Updates a sal in the store with form data
func (s *SalApiService) UpdateSalWithForm(ctx context.Context, empId int64, value string) (openapi.ImplResponse, error) {
	// TODO - update UpdateSalWithForm with the required logic for this service method.
	// Add api_sal_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response openapi.Response(405, {}) or use other options such as http.Ok ...
	//return openapi.Response(405, nil),nil

	return openapi.Response(http.StatusNotImplemented, nil), errors.New("UpdateSalWithForm method not implemented")
}
