/*
 * Employee wage sum
 *
 * Wage sum - demo application with GO language
 *
 * API version: 1.0.0
 * Contact: lsmhun@github
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// EmpApiRouter defines the required methods for binding the api requests to a responses for the EmpApi
// The EmpApiRouter implementation should parse necessary information from the http request,
// pass the data to a EmpApiServicer to perform the required actions, then write the service results to the http response.
type EmpApiRouter interface { 
	GetEmpById(http.ResponseWriter, *http.Request)
}


// EmpApiServicer defines the api actions for the EmpApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type EmpApiServicer interface { 
	GetEmpById(context.Context, int64) (ImplResponse, error)
}
