/*
 * Employee wage sum
 *
 * Wage sum - demo application with GO language
 *
 * API version: 0.3.0
 * Contact: lsmhun@github
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Emp struct {

	Id int64 `json:"id,omitempty"`

	EmpId int64 `json:"empId,omitempty"`

	UserName string `json:"userName,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	MgrId int64 `json:"mgrId,omitempty"`

	// Employee Type
	Type string `json:"type,omitempty"`

	// Employee Status
	Status string `json:"status,omitempty"`
}

// AssertEmpRequired checks if the required fields are not zero-ed
func AssertEmpRequired(obj Emp) error {
	return nil
}

// AssertRecurseEmpRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Emp (e.g. [][]Emp), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEmpRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEmp, ok := obj.(Emp)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEmpRequired(aEmp)
	})
}
